name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-projectname-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-projectname-
    - name: Install node modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Lint
      run: ng lint ngx-br
    - uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 42c27b74a690995c660c6145bf97191267e42d28e5e8eed1158459d097de93b9
      with:
        coverageCommand: ng test ngx-br -- --no-watch --code-coverage --no-progress --browsers=ChromeHeadlessCI
        coverageLocations: ${{github.workspace}}/coverage/ngx-br/lcov.info:lcov
    - name: Build
      run: ng build ngx-br
    - name: Add .nojekyll file to GitHub Pages deployment
      run: touch coverage/ngx-br/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./coverage/ngx-br
